version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: almacencito
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: ezequielbanega/windsurf-frontend:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: always
    labels:
      - "com.containrrr.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 --label-enable
    restart: always

volumes:
  pgdata:
  db_data:
